<section class="container mt-top">
    <div class="col-md-12">
        <div class="row">
            <table class="table">
                <thead>
                    <tr>
                        <td>ID</td>
                        <td>Liga</td>
                        <td>Nome</td>
                        <td>Estatísticas</td>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</section>