<div class="jumbotron">
    <h1><?php echo sprintf('%sOlá%s', '<span class="zf-green">', '</span>'); ?></h1>
</div>

<div class="well">
    <table>        
        <thead>
            <tr>
                <td><input type="text" name="search" size="500"/></td>
                <td><a class="btn btn-success btn-lg"><i class="icon-adjust"></i></a></td>
            </tr>
        </thead>
    </table>
</div>