<div class="jumbotron">
    <h1 class="text-center">Welcome to Corno Stats</h1>
    <p class="text-center">O seu portal de estatísticas!</p>
</div>

<div class="row">
    <div class="col-md-12">                    
        <br/>

        <h4 class="text-center">Jogos de Hoje</h4>

        <br/>

        <div class="row">
            <table id="inplay_match_table" style="display: none;">
                <thead>
                    <tr>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
            </table>
        </div>

        <div class="row">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th>Liga</th>
                        <th>Tempo</th>
                        <th>Casa</th>
                        <th>Placar</th>
                        <th>Visitante</th>
                        <th>Escanteios HT</th>
                        <th>Escanteios FT</th>
                        <th>Total</th>
                        <th>Ataques HT</th>
                        <th>Ataques Totais</th>
                        <th>Chutes</th>
                        <th>ID Jogo</th>
                    </tr>
                </thead>
    
                <tbody id="tbdJogos">
    
                </tbody>
            </table>
        </div>
    </div>
</div>